name: ItemMail
version: ${project.version}
main: io.github.sulkywhale.itemmail.ItemMail
api-version: '1.21'
authors: [ Sulky_Whale ]
commands:
  itemmail:
    aliases: [ mailitem ]
    description: Mail items to other players

permissions:
  itemmail.mail:
    description: Allows players to send and receive mail as well as view the mail GUI
    default: op
    children:
      itemmail.mail.send: true
      itemmail.mail.gui: true
  itemmail.mail.send:
    description: Allows players to send mail
    default: op
  itemmail.mail.gui:
    description: Allows players to view mail GUI and receive mail
    default: op
  itemmail.admin:
    description: Allows admins to view contents of players' mail
    default: op
